language: python
python:
- '2.7'
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
- sudo dpkg -i hugo_0.45.1_Linux-64bit.deb
- sudo chmod 600 id_rsa
script:
- cd codebase
- hugo
- scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../id_rsa -rp public/. codebase@ssh.ocf.berkeley.edu:/home/c/co/codebase/public_html/
before_install:
- openssl aes-256-cbc -K $encrypted_55361f9c588e_key -iv $encrypted_55361f9c588e_iv
  -in id_rsa.enc -out id_rsa -d
branches:
  only:
  - rebrand-2018
